"use client";

import type { HTMLAttributes } from "react";
import type { SelectItemType } from "@/components/base/select/select";

/**
 * List of countries with their respective country code, flag, phone code, and phone mask.
 */
export const countries = [
    {
        name: "Afghanistan",
        code: "AF",
        flag: "https://flagcdn.com/lAF.svg",
        phoneCode: "93",
        phoneMask: "+93-##-###-####",
    },
    {
        name: "Albania",
        code: "AL",
        flag: "https://flagcdn.com/lAL.svg",
        phoneCode: "355",
        phoneMask: "+355 (###) ###-###",
    },
    {
        name: "Algeria",
        code: "DZ",
        flag: "https://flagcdn.com/lDZ.svg",
        phoneCode: "213",
        phoneMask: "+213-##-###-####",
    },
    {
        name: "Andorra",
        code: "AD",
        flag: "https://flagcdn.com/lAD.svg",
        phoneCode: "376",
        phoneMask: "+376-###-###",
    },
    {
        name: "Angola",
        code: "AO",
        flag: "https://flagcdn.com/lAO.svg",
        phoneCode: "244",
        phoneMask: "+244 (###) ###-###",
    },
    {
        name: "Antigua and Barbuda",
        code: "AG",
        flag: "https://flagcdn.com/lAG.svg",
        phoneCode: "+1-268",
        phoneMask: "+1 (268) ###-####",
    },
    {
        name: "Argentina",
        code: "AR",
        flag: "https://flagcdn.com/lAR.svg",
        phoneCode: "54",
        phoneMask: "+54 (###) ###-####",
    },
    {
        name: "Armenia",
        code: "AM",
        flag: "https://flagcdn.com/lAM.svg",
        phoneCode: "374",
        phoneMask: "+374-##-###-###",
    },
    {
        name: "Australia",
        code: "AU",
        flag: "https://flagcdn.com/lAU.svg",
        phoneCode: "61",
        phoneMask: "+61-#-####-####",
    },
    {
        name: "Austria",
        code: "AT",
        flag: "https://flagcdn.com/lAT.svg",
        phoneCode: "43",
        phoneMask: "+43 (###) ###-####",
    },
    {
        name: "Azerbaijan",
        code: "AZ",
        flag: "https://flagcdn.com/lAZ.svg",
        phoneCode: "994",
        phoneMask: "+994-##-###-##-##",
    },
    {
        name: "Bahamas",
        code: "BS",
        flag: "https://flagcdn.com/lBS.svg",
        phoneCode: "+1-242",
        phoneMask: "+1 (242) ###-####",
    },
    {
        name: "Bahrain",
        code: "BH",
        flag: "https://flagcdn.com/lBH.svg",
        phoneCode: "973",
        phoneMask: "+973-####-####",
    },
    {
        name: "Bangladesh",
        code: "BD",
        flag: "https://flagcdn.com/lBD.svg",
        phoneCode: "880",
        phoneMask: "+880-##-###-###",
    },
    {
        name: "Barbados",
        code: "BB",
        flag: "https://flagcdn.com/lBB.svg",
        phoneCode: "+1-246",
        phoneMask: "+1 (246) ###-####",
    },
    {
        name: "Belarus",
        code: "BY",
        flag: "https://flagcdn.com/lBY.svg",
        phoneCode: "375",
        phoneMask: "+375 (##) ###-##-##",
    },
    {
        name: "Belgium",
        code: "BE",
        flag: "https://flagcdn.com/lBE.svg",
        phoneCode: "32",
        phoneMask: "+32 (###) ###-###",
    },
    {
        name: "Belize",
        code: "BZ",
        flag: "https://flagcdn.com/lBZ.svg",
        phoneCode: "501",
        phoneMask: "+501-###-####",
    },
    {
        name: "Benin",
        code: "BJ",
        flag: "https://flagcdn.com/lBJ.svg",
        phoneCode: "229",
        phoneMask: "+229-##-##-####",
    },
    {
        name: "Bhutan",
        code: "BT",
        flag: "https://flagcdn.com/lBT.svg",
        phoneCode: "975",
        phoneMask: "+975-#-###-###",
    },
    {
        name: "Bolivia",
        code: "BO",
        flag: "https://flagcdn.com/lBO.svg",
        phoneCode: "591",
        phoneMask: "+591-#-###-####",
    },
    {
        name: "Bosnia and Herzegovina",
        code: "BA",
        flag: "https://flagcdn.com/lBA.svg",
        phoneCode: "387",
        phoneMask: "+387-##-####",
    },
    {
        name: "Botswana",
        code: "BW",
        flag: "https://flagcdn.com/lBW.svg",
        phoneCode: "267",
        phoneMask: "+267-##-###-###",
    },
    {
        name: "Brazil",
        code: "BR",
        flag: "https://flagcdn.com/lBR.svg",
        phoneCode: "55",
        phoneMask: "+55 (##) 9####-####",
    },
    {
        name: "Brunei",
        code: "BN",
        flag: "https://flagcdn.com/lBN.svg",
        phoneCode: "673",
        phoneMask: "+673-###-####",
    },
    {
        name: "Bulgaria",
        code: "BG",
        flag: "https://flagcdn.com/lBG.svg",
        phoneCode: "359",
        phoneMask: "+359 (###) ###-###",
    },
    {
        name: "Burkina Faso",
        code: "BF",
        flag: "https://flagcdn.com/lBF.svg",
        phoneCode: "226",
        phoneMask: "+226-##-##-####",
    },
    {
        name: "Burundi",
        code: "BI",
        flag: "https://flagcdn.com/lBI.svg",
        phoneCode: "257",
        phoneMask: "+257-##-##-####",
    },
    {
        name: "Cambodia",
        code: "KH",
        flag: "https://flagcdn.com/lKH.svg",
        phoneCode: "855",
        phoneMask: "+855-##-###-###",
    },
    {
        name: "Cameroon",
        code: "CM",
        flag: "https://flagcdn.com/lCM.svg",
        phoneCode: "237",
        phoneMask: "+237-####-####",
    },
    {
        name: "Canada",
        code: "CA",
        flag: "https://flagcdn.com/lCA.svg",
        phoneCode: "1",
        phoneMask: "+1 (###) ###-####",
    },
    {
        name: "Central African Republic",
        code: "CF",
        flag: "https://flagcdn.com/lCF.svg",
        phoneCode: "236",
        phoneMask: "+236-##-##-####",
    },
    {
        name: "Chad",
        code: "TD",
        flag: "https://flagcdn.com/lTD.svg",
        phoneCode: "235",
        phoneMask: "+235-##-##-##-##",
    },
    {
        name: "Chile",
        code: "CL",
        flag: "https://flagcdn.com/lCL.svg",
        phoneCode: "56",
        phoneMask: "+56-#-####-####",
    },
    {
        name: "China",
        code: "CN",
        flag: "https://flagcdn.com/lCN.svg",
        phoneCode: "86",
        phoneMask: "+86-##-#####-#####",
    },
    {
        name: "Colombia",
        code: "CO",
        flag: "https://flagcdn.com/lCO.svg",
        phoneCode: "57",
        phoneMask: "+57 (###) ###-####",
    },
    {
        name: "Comoros",
        code: "KM",
        flag: "https://flagcdn.com/lKM.svg",
        phoneCode: "269",
        phoneMask: "+269-##-#####",
    },
    {
        name: "Costa Rica",
        code: "CR",
        flag: "https://flagcdn.com/lCR.svg",
        phoneCode: "506",
        phoneMask: "+506-####-####",
    },
    {
        name: "Croatia",
        code: "HR",
        flag: "https://flagcdn.com/lHR.svg",
        phoneCode: "385",
        phoneMask: "+385-##-###-###",
    },
    {
        name: "Cuba",
        code: "CU",
        flag: "https://flagcdn.com/lCU.svg",
        phoneCode: "53",
        phoneMask: "+53-#-###-####",
    },
    {
        name: "Cyprus",
        code: "CY",
        flag: "https://flagcdn.com/lCY.svg",
        phoneCode: "357",
        phoneMask: "+357-##-###-###",
    },
    {
        name: "Czech Republic",
        code: "CZ",
        flag: "https://flagcdn.com/lCZ.svg",
        phoneCode: "420",
        phoneMask: "+420 (###) ###-###",
    },
    {
        name: "Democratic Republic of the Congo",
        code: "CD",
        flag: "https://flagcdn.com/lCD.svg",
        phoneCode: "243",
        phoneMask: "+243 (###) ###-###",
    },
    {
        name: "Denmark",
        code: "DK",
        flag: "https://flagcdn.com/lDK.svg",
        phoneCode: "45",
        phoneMask: "+45-##-##-##-##",
    },
    {
        name: "Djibouti",
        code: "DJ",
        flag: "https://flagcdn.com/lDJ.svg",
        phoneCode: "253",
        phoneMask: "+253-##-##-##-##",
    },
    {
        name: "Dominica",
        code: "DM",
        flag: "https://flagcdn.com/lDM.svg",
        phoneCode: "+1-767",
        phoneMask: "+1 (767) ###-####",
    },
    {
        name: "Dominican Republic",
        code: "DO",
        flag: "https://flagcdn.com/lDO.svg",
        phoneCode: "+1-809 and 1-829",
        phoneMask: "+1 (849) ###-####",
    },
    {
        name: "East Timor",
        code: "TL",
        flag: "https://flagcdn.com/lTL.svg",
        phoneCode: "670",
        phoneMask: "+670-78#-#####",
    },
    {
        name: "Ecuador",
        code: "EC",
        flag: "https://flagcdn.com/lEC.svg",
        phoneCode: "593",
        phoneMask: "+593-#-###-####",
    },
    {
        name: "Egypt",
        code: "EG",
        flag: "https://flagcdn.com/lEG.svg",
        phoneCode: "20",
        phoneMask: "+20 (###) ###-####",
    },
    {
        name: "El Salvador",
        code: "SV",
        flag: "https://flagcdn.com/lSV.svg",
        phoneCode: "503",
        phoneMask: "+503-##-##-####",
    },
    {
        name: "Equatorial Guinea",
        code: "GQ",
        flag: "https://flagcdn.com/lGQ.svg",
        phoneCode: "240",
        phoneMask: "+240-##-###-####",
    },
    {
        name: "Eritrea",
        code: "ER",
        flag: "https://flagcdn.com/lER.svg",
        phoneCode: "291",
        phoneMask: "+291-#-###-###",
    },
    {
        name: "Estonia",
        code: "EE",
        flag: "https://flagcdn.com/lEE.svg",
        phoneCode: "372",
        phoneMask: "+372-###-####",
    },
    {
        name: "Eswatini",
        code: "SZ",
        flag: "https://flagcdn.com/lSZ.svg",
        phoneCode: "268",
        phoneMask: "+268-##-##-####",
    },
    {
        name: "Ethiopia",
        code: "ET",
        flag: "https://flagcdn.com/lET.svg",
        phoneCode: "251",
        phoneMask: "+251-##-###-####",
    },
    {
        name: "Fiji",
        code: "FJ",
        flag: "https://flagcdn.com/lFJ.svg",
        phoneCode: "679",
        phoneMask: "+679-##-#####",
    },
    {
        name: "Finland",
        code: "FI",
        flag: "https://flagcdn.com/lFI.svg",
        phoneCode: "358",
        phoneMask: "+358 (###) ###-##-##",
    },
    {
        name: "France",
        code: "FR",
        flag: "https://flagcdn.com/lFR.svg",
        phoneCode: "33",
        phoneMask: "+590 (###) ###-###",
    },
    {
        name: "Gabon",
        code: "GA",
        flag: "https://flagcdn.com/lGA.svg",
        phoneCode: "241",
        phoneMask: "+241-#-##-##-##",
    },
    {
        name: "Gambia",
        code: "GM",
        flag: "https://flagcdn.com/lGM.svg",
        phoneCode: "220",
        phoneMask: "+220 (###) ##-##",
    },
    {
        name: "Georgia",
        code: "GE",
        flag: "https://flagcdn.com/lGE.svg",
        phoneCode: "995",
        phoneMask: "+995 (###) ###-###",
    },
    {
        name: "Germany",
        code: "DE",
        flag: "https://flagcdn.com/lDE.svg",
        phoneCode: "49",
        phoneMask: "+49-###-###",
    },
    {
        name: "Ghana",
        code: "GH",
        flag: "https://flagcdn.com/lGH.svg",
        phoneCode: "233",
        phoneMask: "+233 (###) ###-###",
    },
    {
        name: "Greece",
        code: "GR",
        flag: "https://flagcdn.com/lGR.svg",
        phoneCode: "30",
        phoneMask: "+30 (###) ###-####",
    },
    {
        name: "Grenada",
        code: "GD",
        flag: "https://flagcdn.com/lGD.svg",
        phoneCode: "+1-473",
        phoneMask: "+1 (473) ###-####",
    },
    {
        name: "Guatemala",
        code: "GT",
        flag: "https://flagcdn.com/lGT.svg",
        phoneCode: "502",
        phoneMask: "+502-#-###-####",
    },
    {
        name: "Guinea",
        code: "GN",
        flag: "https://flagcdn.com/lGN.svg",
        phoneCode: "224",
        phoneMask: "+224-##-###-###",
    },
    {
        name: "Guinea-Bissau",
        code: "GW",
        flag: "https://flagcdn.com/lGW.svg",
        phoneCode: "245",
        phoneMask: "+245-#-######",
    },
    {
        name: "Guyana",
        code: "GY",
        flag: "https://flagcdn.com/lGY.svg",
        phoneCode: "592",
        phoneMask: "+592-###-####",
    },
    {
        name: "Haiti",
        code: "HT",
        flag: "https://flagcdn.com/lHT.svg",
        phoneCode: "509",
        phoneMask: "+509-##-##-####",
    },
    {
        name: "Honduras",
        code: "HN",
        flag: "https://flagcdn.com/lHN.svg",
        phoneCode: "504",
        phoneMask: "+504-####-####",
    },
    {
        name: "Hungary",
        code: "HU",
        flag: "https://flagcdn.com/lHU.svg",
        phoneCode: "36",
        phoneMask: "+36 (###) ###-###",
    },
    {
        name: "Iceland",
        code: "IS",
        flag: "https://flagcdn.com/lIS.svg",
        phoneCode: "354",
        phoneMask: "+354-###-####",
    },
    {
        name: "India",
        code: "IN",
        flag: "https://flagcdn.com/lIN.svg",
        phoneCode: "91",
        phoneMask: "+91 (####) ###-###",
    },
    {
        name: "Indonesia",
        code: "ID",
        flag: "https://flagcdn.com/lID.svg",
        phoneCode: "62",
        phoneMask: "+62 (8##) ###-##-###",
    },
    {
        name: "Iran",
        code: "IR",
        flag: "https://flagcdn.com/lIR.svg",
        phoneCode: "98",
        phoneMask: "+98 (###) ###-####",
    },
    {
        name: "Iraq",
        code: "IQ",
        flag: "https://flagcdn.com/lIQ.svg",
        phoneCode: "964",
        phoneMask: "+964 (###) ###-####",
    },
    {
        name: "Ireland",
        code: "IE",
        flag: "https://flagcdn.com/lIE.svg",
        phoneCode: "353",
        phoneMask: "+353 (###) ###-###",
    },
    {
        name: "Israel",
        code: "IL",
        flag: "https://flagcdn.com/lIL.svg",
        phoneCode: "972",
        phoneMask: "+972-#-###-####",
    },
    {
        name: "Italy",
        code: "IT",
        flag: "https://flagcdn.com/lIT.svg",
        phoneCode: "39",
        phoneMask: "+39 (###) ####-###",
    },
    {
        name: "Jamaica",
        code: "JM",
        flag: "https://flagcdn.com/lJM.svg",
        phoneCode: "+1-876",
        phoneMask: "+1 (876) ###-####",
    },
    {
        name: "Japan",
        code: "JP",
        flag: "https://flagcdn.com/lJP.svg",
        phoneCode: "81",
        phoneMask: "+81 (###) ###-###",
    },
    {
        name: "Jordan",
        code: "JO",
        flag: "https://flagcdn.com/lJO.svg",
        phoneCode: "962",
        phoneMask: "+962-#-####-####",
    },
    {
        name: "Kazakhstan",
        code: "KZ",
        flag: "https://flagcdn.com/lKZ.svg",
        phoneCode: "7",
        phoneMask: "+7 (7##) ###-##-##",
    },
    {
        name: "Kenya",
        code: "KE",
        flag: "https://flagcdn.com/lKE.svg",
        phoneCode: "254",
        phoneMask: "+254-###-######",
    },
    {
        name: "Kiribati",
        code: "KI",
        flag: "https://flagcdn.com/lKI.svg",
        phoneCode: "686",
        phoneMask: "+686-##-###",
    },
    {
        name: "Kuwait",
        code: "KW",
        flag: "https://flagcdn.com/lKW.svg",
        phoneCode: "965",
        phoneMask: "+965-####-####",
    },
    {
        name: "Kyrgyzstan",
        code: "KG",
        flag: "https://flagcdn.com/lKG.svg",
        phoneCode: "996",
        phoneMask: "+996 (###) ###-###",
    },
    {
        name: "Laos",
        code: "LA",
        flag: "https://flagcdn.com/lLA.svg",
        phoneCode: "856",
        phoneMask: "+856-##-###-###",
    },
    {
        name: "Latvia",
        code: "LV",
        flag: "https://flagcdn.com/lLV.svg",
        phoneCode: "371",
        phoneMask: "+371-##-###-###",
    },
    {
        name: "Lebanon",
        code: "LB",
        flag: "https://flagcdn.com/lLB.svg",
        phoneCode: "961",
        phoneMask: "+961-#-###-###",
    },
    {
        name: "Lesotho",
        code: "LS",
        flag: "https://flagcdn.com/lLS.svg",
        phoneCode: "266",
        phoneMask: "+266-#-###-####",
    },
    {
        name: "Liberia",
        code: "LR",
        flag: "https://flagcdn.com/lLR.svg",
        phoneCode: "231",
        phoneMask: "+231-##-###-###",
    },
    {
        name: "Libya",
        code: "LY",
        flag: "https://flagcdn.com/lLY.svg",
        phoneCode: "218",
        phoneMask: "+218-21-###-####",
    },
    {
        name: "Liechtenstein",
        code: "LI",
        flag: "https://flagcdn.com/lLI.svg",
        phoneCode: "423",
        phoneMask: "+423 (###) ###-####",
    },
    {
        name: "Lithuania",
        code: "LT",
        flag: "https://flagcdn.com/lLT.svg",
        phoneCode: "370",
        phoneMask: "+370 (###) ##-###",
    },
    {
        name: "Luxembourg",
        code: "LU",
        flag: "https://flagcdn.com/lLU.svg",
        phoneCode: "352",
        phoneMask: "+352 (###) ###-###",
    },
    {
        name: "Madagascar",
        code: "MG",
        flag: "https://flagcdn.com/lMG.svg",
        phoneCode: "261",
        phoneMask: "+261-##-##-#####",
    },
    {
        name: "Malawi",
        code: "MW",
        flag: "https://flagcdn.com/lMW.svg",
        phoneCode: "265",
        phoneMask: "+265-#-####-####",
    },
    {
        name: "Malaysia",
        code: "MY",
        flag: "https://flagcdn.com/lMY.svg",
        phoneCode: "60",
        phoneMask: "+60-#-###-###",
    },
    {
        name: "Maldives",
        code: "MV",
        flag: "https://flagcdn.com/lMV.svg",
        phoneCode: "960",
        phoneMask: "+960-###-####",
    },
    {
        name: "Mali",
        code: "ML",
        flag: "https://flagcdn.com/lML.svg",
        phoneCode: "223",
        phoneMask: "+223-##-##-####",
    },
    {
        name: "Malta",
        code: "MT",
        flag: "https://flagcdn.com/lMT.svg",
        phoneCode: "356",
        phoneMask: "+356-####-####",
    },
    {
        name: "Marshall Islands",
        code: "MH",
        flag: "https://flagcdn.com/lMH.svg",
        phoneCode: "692",
        phoneMask: "+692-###-####",
    },
    {
        name: "Mauritania",
        code: "MR",
        flag: "https://flagcdn.com/lMR.svg",
        phoneCode: "222",
        phoneMask: "+222-##-##-####",
    },
    {
        name: "Mauritius",
        code: "MU",
        flag: "https://flagcdn.com/lMU.svg",
        phoneCode: "230",
        phoneMask: "+230-###-####",
    },
    {
        name: "Mexico",
        code: "MX",
        flag: "https://flagcdn.com/lMX.svg",
        phoneCode: "52",
        phoneMask: "+52-##-##-####",
    },
    {
        name: "Micronesia",
        code: "FM",
        flag: "https://flagcdn.com/lFM.svg",
        phoneCode: "691",
        phoneMask: "+691-###-####",
    },
    {
        name: "Moldova",
        code: "MD",
        flag: "https://flagcdn.com/lMD.svg",
        phoneCode: "373",
        phoneMask: "+373-####-####",
    },
    {
        name: "Monaco",
        code: "MC",
        flag: "https://flagcdn.com/lMC.svg",
        phoneCode: "377",
        phoneMask: "+377-##-###-###",
    },
    {
        name: "Mongolia",
        code: "MN",
        flag: "https://flagcdn.com/lMN.svg",
        phoneCode: "976",
        phoneMask: "+976-##-##-####",
    },
    {
        name: "Montenegro",
        code: "ME",
        flag: "https://flagcdn.com/lME.svg",
        phoneCode: "382",
        phoneMask: "+382-##-###-###",
    },
    {
        name: "Morocco",
        code: "MA",
        flag: "https://flagcdn.com/lMA.svg",
        phoneCode: "212",
        phoneMask: "+212-##-####-###",
    },
    {
        name: "Mozambique",
        code: "MZ",
        flag: "https://flagcdn.com/lMZ.svg",
        phoneCode: "258",
        phoneMask: "+258-##-###-###",
    },
    {
        name: "Myanmar",
        code: "MM",
        flag: "https://flagcdn.com/lMM.svg",
        phoneCode: "95",
        phoneMask: "+95-###-###",
    },
    {
        name: "Namibia",
        code: "NA",
        flag: "https://flagcdn.com/lNA.svg",
        phoneCode: "264",
        phoneMask: "+264-##-###-####",
    },
    {
        name: "Nauru",
        code: "NR",
        flag: "https://flagcdn.com/lNR.svg",
        phoneCode: "674",
        phoneMask: "+674-###-####",
    },
    {
        name: "Nepal",
        code: "NP",
        flag: "https://flagcdn.com/lNP.svg",
        phoneCode: "977",
        phoneMask: "+977-##-###-###",
    },
    {
        name: "Netherlands",
        code: "NL",
        flag: "https://flagcdn.com/lNL.svg",
        phoneCode: "31",
        phoneMask: "+31-##-###-####",
    },
    {
        name: "New Zealand",
        code: "NZ",
        flag: "https://flagcdn.com/lNZ.svg",
        phoneCode: "64",
        phoneMask: "+64 (###) ###-####",
    },
    {
        name: "Nicaragua",
        code: "NI",
        flag: "https://flagcdn.com/lNI.svg",
        phoneCode: "505",
        phoneMask: "+505-####-####",
    },
    {
        name: "Niger",
        code: "NE",
        flag: "https://flagcdn.com/lNE.svg",
        phoneCode: "227",
        phoneMask: "+227-##-##-####",
    },
    {
        name: "Nigeria",
        code: "NG",
        flag: "https://flagcdn.com/lNG.svg",
        phoneCode: "234",
        phoneMask: "+234 (###) ###-####",
    },
    {
        name: "North Korea",
        code: "KP",
        flag: "https://flagcdn.com/lKP.svg",
        phoneCode: "850",
        phoneMask: "+850-####-#############",
    },
    {
        name: "North Macedonia",
        code: "MK",
        flag: "https://flagcdn.com/lMK.svg",
        phoneCode: "389",
        phoneMask: "+389-##-###-###",
    },
    {
        name: "Norway",
        code: "NO",
        flag: "https://flagcdn.com/lNO.svg",
        phoneCode: "47",
        phoneMask: "+47 (###) ##-###",
    },
    {
        name: "Oman",
        code: "OM",
        flag: "https://flagcdn.com/lOM.svg",
        phoneCode: "968",
        phoneMask: "+968-##-###-###",
    },
    {
        name: "Pakistan",
        code: "PK",
        flag: "https://flagcdn.com/lPK.svg",
        phoneCode: "92",
        phoneMask: "+92 (###) ###-####",
    },
    {
        name: "Palau",
        code: "PW",
        flag: "https://flagcdn.com/lPW.svg",
        phoneCode: "680",
        phoneMask: "+680-###-####",
    },
    {
        name: "Panama",
        code: "PA",
        flag: "https://flagcdn.com/lPA.svg",
        phoneCode: "507",
        phoneMask: "+507-###-####",
    },
    {
        name: "Papua New Guinea",
        code: "PG",
        flag: "https://flagcdn.com/lPG.svg",
        phoneCode: "675",
        phoneMask: "+675 (###) ##-###",
    },
    {
        name: "Paraguay",
        code: "PY",
        flag: "https://flagcdn.com/lPY.svg",
        phoneCode: "595",
        phoneMask: "+595 (###) ###-###",
    },
    {
        name: "Peru",
        code: "PE",
        flag: "https://flagcdn.com/lPE.svg",
        phoneCode: "51",
        phoneMask: "+51 (###) ###-###",
    },
    {
        name: "Philippines",
        code: "PH",
        flag: "https://flagcdn.com/lPH.svg",
        phoneCode: "63",
        phoneMask: "+63 (###) ###-####",
    },
    {
        name: "Poland",
        code: "PL",
        flag: "https://flagcdn.com/lPL.svg",
        phoneCode: "48",
        phoneMask: "+48 (###) ###-###",
    },
    {
        name: "Portugal",
        code: "PT",
        flag: "https://flagcdn.com/lPT.svg",
        phoneCode: "351",
        phoneMask: "+351-##-###-####",
    },
    {
        name: "Qatar",
        code: "QA",
        flag: "https://flagcdn.com/lQA.svg",
        phoneCode: "974",
        phoneMask: "+974-####-####",
    },
    {
        name: "Romania",
        code: "RO",
        flag: "https://flagcdn.com/lRO.svg",
        phoneCode: "40",
        phoneMask: "+40-##-###-####",
    },
    {
        name: "Russia",
        code: "RU",
        flag: "https://flagcdn.com/lRU.svg",
        phoneCode: "7",
        phoneMask: "+7 (###) ###-##-##",
    },
    {
        name: "Rwanda",
        code: "RW",
        flag: "https://flagcdn.com/lRW.svg",
        phoneCode: "250",
        phoneMask: "+250 (###) ###-###",
    },
    {
        name: "Saint Kitts and Nevis",
        code: "KN",
        flag: "https://flagcdn.com/lKN.svg",
        phoneCode: "+1-869",
        phoneMask: "+1 (869) ###-####",
    },
    {
        name: "Saint Lucia",
        code: "LC",
        flag: "https://flagcdn.com/lLC.svg",
        phoneCode: "+1-758",
        phoneMask: "+1 (758) ###-####",
    },
    {
        name: "Saint Vincent and the Grenadines",
        code: "VC",
        flag: "https://flagcdn.com/lVC.svg",
        phoneCode: "+1-784",
        phoneMask: "+1 (784) ###-####",
    },
    {
        name: "Samoa",
        code: "WS",
        flag: "https://flagcdn.com/lWS.svg",
        phoneCode: "685",
        phoneMask: "+685-##-####",
    },
    {
        name: "San Marino",
        code: "SM",
        flag: "https://flagcdn.com/lSM.svg",
        phoneCode: "378",
        phoneMask: "+378-####-######",
    },
    {
        name: "Sao Tome and Principe",
        code: "ST",
        flag: "https://flagcdn.com/lST.svg",
        phoneCode: "239",
        phoneMask: "+239-##-#####",
    },
    {
        name: "Saudi Arabia",
        code: "SA",
        flag: "https://flagcdn.com/lSA.svg",
        phoneCode: "966",
        phoneMask: "+966-#-###-####",
    },
    {
        name: "Senegal",
        code: "SN",
        flag: "https://flagcdn.com/lSN.svg",
        phoneCode: "221",
        phoneMask: "+221-##-###-####",
    },
    {
        name: "Serbia",
        code: "RS",
        flag: "https://flagcdn.com/lRS.svg",
        phoneCode: "381",
        phoneMask: "+381-##-###-####",
    },
    {
        name: "Seychelles",
        code: "SC",
        flag: "https://flagcdn.com/lSC.svg",
        phoneCode: "248",
        phoneMask: "+248-#-###-###",
    },
    {
        name: "Sierra Leone",
        code: "SL",
        flag: "https://flagcdn.com/lSL.svg",
        phoneCode: "232",
        phoneMask: "+232-##-######",
    },
    {
        name: "Singapore",
        code: "SG",
        flag: "https://flagcdn.com/lSG.svg",
        phoneCode: "65",
        phoneMask: "+65-####-####",
    },
    {
        name: "Slovakia",
        code: "SK",
        flag: "https://flagcdn.com/lSK.svg",
        phoneCode: "421",
        phoneMask: "+421 (###) ###-###",
    },
    {
        name: "Slovenia",
        code: "SI",
        flag: "https://flagcdn.com/lSI.svg",
        phoneCode: "386",
        phoneMask: "+386-##-###-###",
    },
    {
        name: "Solomon Islands",
        code: "SB",
        flag: "https://flagcdn.com/lSB.svg",
        phoneCode: "677",
        phoneMask: "+677-#####",
    },
    {
        name: "Somalia",
        code: "SO",
        flag: "https://flagcdn.com/lSO.svg",
        phoneCode: "252",
        phoneMask: "+252-#-###-###",
    },
    {
        name: "South Africa",
        code: "ZA",
        flag: "https://flagcdn.com/lZA.svg",
        phoneCode: "27",
        phoneMask: "+27-##-###-####",
    },
    {
        name: "South Korea",
        code: "KR",
        flag: "https://flagcdn.com/lKR.svg",
        phoneCode: "82",
        phoneMask: "+82-##-###-####",
    },
    {
        name: "South Sudan",
        code: "SS",
        flag: "https://flagcdn.com/lSS.svg",
        phoneCode: "211",
        phoneMask: "+211-##-###-####",
    },
    {
        name: "Spain",
        code: "ES",
        flag: "https://flagcdn.com/lES.svg",
        phoneCode: "34",
        phoneMask: "+34 (###) ###-###",
    },
    {
        name: "Sri Lanka",
        code: "LK",
        flag: "https://flagcdn.com/lLK.svg",
        phoneCode: "94",
        phoneMask: "+94-##-###-####",
    },
    {
        name: "Suriname",
        code: "SR",
        flag: "https://flagcdn.com/lSR.svg",
        phoneCode: "597",
        phoneMask: "+597-###-###",
    },
    {
        name: "Sweden",
        code: "SE",
        flag: "https://flagcdn.com/lSE.svg",
        phoneCode: "46",
        phoneMask: "+46-##-###-####",
    },
    {
        name: "Switzerland",
        code: "CH",
        flag: "https://flagcdn.com/lCH.svg",
        phoneCode: "41",
        phoneMask: "+41-##-###-####",
    },
    {
        name: "Syria",
        code: "SY",
        flag: "https://flagcdn.com/lSY.svg",
        phoneCode: "963",
        phoneMask: "+963-##-####-###",
    },
    {
        name: "Tajikistan",
        code: "TJ",
        flag: "https://flagcdn.com/lTJ.svg",
        phoneCode: "992",
        phoneMask: "+992-##-###-####",
    },
    {
        name: "Tanzania",
        code: "TZ",
        flag: "https://flagcdn.com/lTZ.svg",
        phoneCode: "255",
        phoneMask: "+255-##-###-####",
    },
    {
        name: "Thailand",
        code: "TH",
        flag: "https://flagcdn.com/lTH.svg",
        phoneCode: "66",
        phoneMask: "+66-##-###-###",
    },
    {
        name: "Togo",
        code: "TG",
        flag: "https://flagcdn.com/lTG.svg",
        phoneCode: "228",
        phoneMask: "+228-##-###-###",
    },
    {
        name: "Tonga",
        code: "TO",
        flag: "https://flagcdn.com/lTO.svg",
        phoneCode: "676",
        phoneMask: "+676-#####",
    },
    {
        name: "Trinidad and Tobago",
        code: "TT",
        flag: "https://flagcdn.com/lTT.svg",
        phoneCode: "+1-868",
        phoneMask: "+1 (868) ###-####",
    },
    {
        name: "Tunisia",
        code: "TN",
        flag: "https://flagcdn.com/lTN.svg",
        phoneCode: "216",
        phoneMask: "+216-##-###-###",
    },
    {
        name: "Turkey",
        code: "TR",
        flag: "https://flagcdn.com/lTR.svg",
        phoneCode: "90",
        phoneMask: "+90 (###) ###-####",
    },
    {
        name: "Turkmenistan",
        code: "TM",
        flag: "https://flagcdn.com/lTM.svg",
        phoneCode: "993",
        phoneMask: "+993-#-###-####",
    },
    {
        name: "Tuvalu",
        code: "TV",
        flag: "https://flagcdn.com/lTV.svg",
        phoneCode: "688",
        phoneMask: "+688-2####",
    },
    {
        name: "Uganda",
        code: "UG",
        flag: "https://flagcdn.com/lUG.svg",
        phoneCode: "256",
        phoneMask: "+256 (###) ###-###",
    },
    {
        name: "Ukraine",
        code: "UA",
        flag: "https://flagcdn.com/lUA.svg",
        phoneCode: "380",
        phoneMask: "+380 (##) ###-##-##",
    },
    {
        name: "United Arab Emirates",
        code: "AE",
        flag: "https://flagcdn.com/lAE.svg",
        phoneCode: "971",
        phoneMask: "+971-#-###-####",
    },
    {
        name: "United Kingdom",
        code: "GB",
        flag: "https://flagcdn.com/lGB.svg",
        phoneCode: "44",
    },
    {
        name: "United States",
        code: "US",
        flag: "https://flagcdn.com/lUS.svg",
        phoneCode: "1",
        phoneMask: "+1 (###) ###-####",
    },
    {
        name: "Uruguay",
        code: "UY",
        flag: "https://flagcdn.com/lUY.svg",
        phoneCode: "598",
        phoneMask: "+598-#-###-##-##",
    },
    {
        name: "Uzbekistan",
        code: "UZ",
        flag: "https://flagcdn.com/lUZ.svg",
        phoneCode: "998",
        phoneMask: "+998-##-###-####",
    },
    {
        name: "Vanuatu",
        code: "VU",
        flag: "https://flagcdn.com/lVU.svg",
        phoneCode: "678",
        phoneMask: "+678-#####",
    },
    {
        name: "Venezuela",
        code: "VE",
        flag: "https://flagcdn.com/lVE.svg",
        phoneCode: "58",
        phoneMask: "+58 (###) ###-####",
    },
    {
        name: "Vietnam",
        code: "VN",
        flag: "https://flagcdn.com/lVN.svg",
        phoneCode: "84",
        phoneMask: "+84 (###) ####-###",
    },
    {
        name: "Yemen",
        code: "YE",
        flag: "https://flagcdn.com/lYE.svg",
        phoneCode: "967",
        phoneMask: "+967-##-###-###",
    },
    {
        name: "Zambia",
        code: "ZM",
        flag: "https://flagcdn.com/lZM.svg",
        phoneCode: "260",
        phoneMask: "+260-##-###-####",
    },
    {
        name: "Zimbabwe",
        code: "ZW",
        flag: "https://flagcdn.com/lZW.svg",
        phoneCode: "263",
        phoneMask: "+263-#-######",
    },
];

/**
 * Phone code options for the select component.
 */
export const phoneCodeOptions: SelectItemType[] = countries.map((country) => ({
    id: country.code,
    label: country.code,
}));

/**
 * Country options for the select component.
 */
export const countriesOptions: SelectItemType[] = countries.map((country) => ({
    id: country.code,
    label: country.name,
    icon: (props: HTMLAttributes<HTMLImageElement>) => <img {...props} src={country.flag} alt={`${country.name} flag`} />,
}));

export default countries;
